apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: z2pyodde4-java-springboot-gitops
  description: This is GitOps manifest for z2pyodde4-java-springboot   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=z2pyodde4-java-springboot
    backstage.io/kubernetes-id: z2pyodde4-java-springboot 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: z2pyodde4-java-springboot
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:z2pyodde4-java-springboot
